BaseURL: "http://imint.se"
languageCode: "sv-se"
title: "Imint"
MetaDataFormat: "toml"
blackfriday:
  extensions:
    - hardLineBreak
menu:
  main:
    - name: "LÃ¶sningar"
      weight: 15
      URL: "/losningar/"
    - name: "Nyheter"
      weight: 15
      URL: "/nyheter/"
